# Generated by Django 4.2.7 on 2026-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_patient_email'),
    ]

    operations = []
